# Generated by Django 4.1.5 on 2023-02-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewpost.category'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
