# Generated by Django 4.1.5 on 2023-02-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0004_filemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='author',
        ),
    ]
