# Generated by Django 4.1.5 on 2023-02-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0006_hiragana'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hiragana',
        ),
    ]
